language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - frontend/node_modules
    - backend/node_modules
env:
  - TEST_DIR=frontend
  - TEST_DIR=backend DATABASE_NAME="testingDatabase" DATABASE_PASSWORD=""
services:
  - postgresql
before_script:
  - psql -c 'create database testingDatabase;' -U postgres
  - cd $TEST_DIR
  - npm install
  - if [ "$TEST_DIR" = "backend" ]; then ./node_modules/.bin/knex migrate:latest; else echo 0; fi
script: npm test
