language: node_js
node_js:
  - "stable"
cache:
  directories:
  - frontend/node_modules
  - backend/node_modules
env:
  - TEST_DIR=frontend
  - TEST_DIR=backend
services:
  - postgresql
script: cd $TEST_DIR && npm install && npm test
