language: node_js
node_js:
  - "stable"
cache:
  directories:
  - frontend/node_modules
  - backend/node_modules
env:
  - TEST_DIR=frontend
  - TEST_DIR=backend
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script: cd $TEST_DIR && npm install && npm test
